title: Zijian
url: "https://zijian0615.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: zjzhang2023@hkbu.edu.hk
footer_text: "zjzhang2023@hkbu.edu.hk   ｜  224 Waterloo Road, Kowloon Tong"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resources/Vitae_Zijian_CS.pdf"
 - name: "Research"
   link: "research"
 - name: "?"
   link: "contact"
